"""
team_config.py

Port of teamConfig.js — all 10 IPL team personalities.
These drive squad targets, archetypeWeights, bidding personality,
and playing XI shapes for the environment and agents.
"""

from typing import Dict, List

RETENTION_SLABS = [18, 14, 11]  # Crore per retention slot (max 3)

TEAM_CONFIGS: Dict[str, dict] = {
    "MI": {
        "id": "MI",
        "name": "Mumbai Indians",
        "short_name": "MI",
        "color": "#004B8D",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 7, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 2},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 5, "max": 7, "ideal": 6},
            "SPIN":   {"min": 2, "max": 3, "ideal": 2},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 3, "SPIN": 1},
        "archetype_weights": {
            "Death Specialist": 25, "True All-rounder": 22, "Aggressor": 20,
            "Power Hitter": 18, "Powerplay Enforcer": 18, "Finisher": 16,
            "Bowling All-rounder": 14, "Anchor": 12, "Economy Seamer": 10,
            "Wicket Taker": 10, "Accumulator": 8, "Batting All-rounder": 8,
            "Impact Player": 8, "Economy King": 6, "Utility Seamer": 5, "Utility Spinner": 4,
        },
        "preferred_traits": ["Big Match Player", "Leader", "Clutch", "Match Winner", "Consistent"],
        "avoided_traits":   ["Inconsistent", "Volatile"],
        "scare_bid_tendency": "high",
        "budget_aggressiveness": "aggressive",
        "value_ceiling_cr": 22,
        "marquee_bonus_multi": 1.35,
        "retentions": ["Jasprit Bumrah", "Rohit Sharma", "Suryakumar Yadav"],
        "rival_teams": ["CSK"],
        "philosophy": "Dynasty. Pedigree. Winning culture.",
    },

    "CSK": {
        "id": "CSK",
        "name": "Chennai Super Kings",
        "short_name": "CSK",
        "color": "#F7B700",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 6, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 4, "max": 6, "ideal": 5},
            "SPIN":   {"min": 2, "max": 3, "ideal": 4},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 2, "SPIN": 2},
        "archetype_weights": {
            "Finisher": 25, "Economy King": 24, "True All-rounder": 22, "Anchor": 20,
            "Economy Seamer": 18, "Bowling All-rounder": 16, "Death Specialist": 15,
            "Accumulator": 14, "Batting All-rounder": 12, "Wicket Taker": 10,
            "Utility Spinner": 12, "Utility Seamer": 10, "Aggressor": 8,
            "Power Hitter": 6, "Impact Player": 6, "Powerplay Enforcer": 8,
        },
        "preferred_traits": ["Veteran", "Clutch", "Pressure Player", "Leader", "Technically Sound"],
        "avoided_traits":   ["Volatile", "Temperamental"],
        "scare_bid_tendency": "low",
        "budget_aggressiveness": "conservative",
        "value_ceiling_cr": 18,
        "marquee_bonus_multi": 1.1,
        "retentions": ["MS Dhoni", "Ravindra Jadeja", "Ruturaj Gaikwad"],
        "rival_teams": ["MI"],
        "philosophy": "Patient and calm. Let others overbid, then swoop late.",
    },

    "RCB": {
        "id": "RCB",
        "name": "Royal Challengers Bengaluru",
        "short_name": "RCB",
        "color": "#EC1C24",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 5, "max": 8, "ideal": 7},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 4, "max": 6, "ideal": 5},
            "SPIN":   {"min": 2, "max": 3, "ideal": 2},
        },
        "playing_xi": {"BAT": 5, "WK-BAT": 1, "ALL": 2, "PACE": 2, "SPIN": 1},
        "archetype_weights": {
            "Aggressor": 25, "Power Hitter": 25, "Anchor": 20, "Impact Player": 18,
            "Batting All-rounder": 16, "Finisher": 15, "True All-rounder": 12,
            "Death Specialist": 10, "Wicket Taker": 8, "Powerplay Enforcer": 8,
            "Economy King": 6, "Bowling All-rounder": 6, "Economy Seamer": 4,
            "Utility Seamer": 3, "Utility Spinner": 3, "Accumulator": 5,
        },
        "preferred_traits": ["Explosive", "Aggressive", "Big Match Player", "T20 Specialist"],
        "avoided_traits":   ["Economy Focused", "Consistent"],
        "scare_bid_tendency": "very_high",
        "budget_aggressiveness": "aggressive",
        "value_ceiling_cr": 25,
        "marquee_bonus_multi": 1.5,
        "retentions": ["Virat Kohli", "Mohammed Siraj", "Phil Salt"],
        "rival_teams": ["KKR"],
        "philosophy": "Star power and spectacle.",
    },

    "KKR": {
        "id": "KKR",
        "name": "Kolkata Knight Riders",
        "short_name": "KKR",
        "color": "#3A225D",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 6, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 4},
            "PACE":   {"min": 4, "max": 6, "ideal": 5},
            "SPIN":   {"min": 2, "max": 3, "ideal": 3},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 2, "SPIN": 2},
        "archetype_weights": {
            "Impact Player": 25, "Wicket Taker": 22, "True All-rounder": 20,
            "Batting All-rounder": 18, "Economy King": 16, "Aggressor": 15,
            "Death Specialist": 14, "Power Hitter": 12, "Bowling All-rounder": 12,
            "Utility Spinner": 10, "Powerplay Enforcer": 10, "Finisher": 8,
            "Anchor": 8, "Accumulator": 6, "Economy Seamer": 8, "Utility Seamer": 6,
        },
        "preferred_traits": ["IPL Veteran", "T20 Specialist", "Explosive"],
        "avoided_traits":   ["Inconsistent"],
        "scare_bid_tendency": "low",
        "budget_aggressiveness": "balanced",
        "value_ceiling_cr": 16,
        "marquee_bonus_multi": 0.9,
        "retentions": ["Shreyas Iyer", "Sunil Narine", "Andre Russell"],
        "rival_teams": ["RCB"],
        "philosophy": "Analytics-first. Find gems others overlook.",
    },

    "DC": {
        "id": "DC",
        "name": "Delhi Capitals",
        "short_name": "DC",
        "color": "#0078BC",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 6, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 5, "max": 8, "ideal": 7},
            "SPIN":   {"min": 2, "max": 3, "ideal": 2},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 3, "SPIN": 1},
        "archetype_weights": {
            "Aggressor": 24, "Powerplay Enforcer": 22, "Death Specialist": 20,
            "Power Hitter": 18, "Impact Player": 16, "Batting All-rounder": 14,
            "Wicket Taker": 14, "Finisher": 12, "True All-rounder": 10,
            "Anchor": 10, "Bowling All-rounder": 10, "Economy King": 8,
            "Accumulator": 6, "Economy Seamer": 8, "Utility Seamer": 6, "Utility Spinner": 6,
        },
        "preferred_traits": ["Explosive", "Pace Threat", "T20 Specialist", "Big Match Player"],
        "avoided_traits":   ["Veteran"],
        "scare_bid_tendency": "medium",
        "budget_aggressiveness": "balanced",
        "value_ceiling_cr": 18,
        "marquee_bonus_multi": 1.15,
        "retentions": ["Rishabh Pant", "Axar Patel", "Kuldeep Yadav"],
        "rival_teams": ["PBKS"],
        "philosophy": "Youth and energy. Under-25 Indian pace is the priority.",
    },

    "RR": {
        "id": "RR",
        "name": "Rajasthan Royals",
        "short_name": "RR",
        "color": "#EA1A85",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 6, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 4},
            "PACE":   {"min": 4, "max": 6, "ideal": 5},
            "SPIN":   {"min": 2, "max": 3, "ideal": 3},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 2, "SPIN": 2},
        "archetype_weights": {
            "Economy King": 25, "True All-rounder": 22, "Wicket Taker": 20,
            "Bowling All-rounder": 18, "Accumulator": 15, "Anchor": 14,
            "Death Specialist": 14, "Economy Seamer": 16, "Batting All-rounder": 12,
            "Finisher": 10, "Impact Player": 10, "Aggressor": 8,
            "Powerplay Enforcer": 8, "Utility Spinner": 12, "Power Hitter": 6, "Utility Seamer": 10,
        },
        "preferred_traits": ["Technically Sound", "Consistent", "Economy Focused"],
        "avoided_traits":   ["Volatile", "Temperamental"],
        "scare_bid_tendency": "very_low",
        "budget_aggressiveness": "conservative",
        "value_ceiling_cr": 14,
        "marquee_bonus_multi": 0.8,
        "retentions": ["Sanju Samson", "Yashasvi Jaiswal", "Riyan Parag"],
        "rival_teams": ["PBKS"],
        "philosophy": "Moneyball. Strict value ceiling. Never emotional.",
    },

    "SRH": {
        "id": "SRH",
        "name": "Sunrisers Hyderabad",
        "short_name": "SRH",
        "color": "#F7A721",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 3, "max": 5, "ideal": 4},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 6, "max": 9, "ideal": 8},
            "SPIN":   {"min": 2, "max": 3, "ideal": 2},
        },
        "playing_xi": {"BAT": 3, "WK-BAT": 1, "ALL": 2, "PACE": 4, "SPIN": 1},
        "archetype_weights": {
            "Death Specialist": 25, "Powerplay Enforcer": 25, "Economy Seamer": 20,
            "Aggressor": 18, "Power Hitter": 18, "True All-rounder": 14,
            "Wicket Taker": 12, "Bowling All-rounder": 12, "Finisher": 10,
            "Impact Player": 10, "Economy King": 8, "Utility Seamer": 10,
            "Batting All-rounder": 6, "Anchor": 4, "Accumulator": 4, "Utility Spinner": 6,
        },
        "preferred_traits": ["Pace Threat", "Death Bowler", "Explosive", "Big Match Player"],
        "avoided_traits":   ["Economy Focused"],
        "scare_bid_tendency": "high",
        "budget_aggressiveness": "aggressive",
        "value_ceiling_cr": 20,
        "marquee_bonus_multi": 1.2,
        "retentions": ["Travis Head", "Heinrich Klaasen", "Pat Cummins"],
        "rival_teams": ["MI", "PBKS"],
        "philosophy": "Pace fortress. Will overpay for elite seamers.",
    },

    "PBKS": {
        "id": "PBKS",
        "name": "Punjab Kings",
        "short_name": "PBKS",
        "color": "#ED1B24",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 5, "max": 8, "ideal": 7},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 4, "max": 6, "ideal": 5},
            "SPIN":   {"min": 2, "max": 3, "ideal": 2},
        },
        "playing_xi": {"BAT": 5, "WK-BAT": 1, "ALL": 1, "PACE": 3, "SPIN": 1},
        "archetype_weights": {
            "Power Hitter": 25, "Aggressor": 24, "Impact Player": 20, "Finisher": 18,
            "Batting All-rounder": 16, "True All-rounder": 12, "Death Specialist": 10,
            "Powerplay Enforcer": 10, "Wicket Taker": 8, "Economy King": 6,
            "Anchor": 4, "Bowling All-rounder": 8, "Economy Seamer": 4,
            "Accumulator": 3, "Utility Seamer": 4, "Utility Spinner": 4,
        },
        "preferred_traits": ["Explosive", "Aggressive", "T20 Specialist", "Big Match Player"],
        "avoided_traits":   ["Economy Focused", "Technically Sound"],
        "scare_bid_tendency": "very_high",
        "budget_aggressiveness": "aggressive",
        "value_ceiling_cr": 24,
        "marquee_bonus_multi": 1.4,
        "retentions": ["Arshdeep Singh", "Shashank Singh", "Prabhsimran Singh"],
        "rival_teams": ["DC", "RR", "SRH"],
        "philosophy": "Chaotic and emotional. Blows budget early, scrambles late.",
    },

    "GT": {
        "id": "GT",
        "name": "Gujarat Titans",
        "short_name": "GT",
        "color": "#1C1C1C",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 6, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 4},
            "PACE":   {"min": 4, "max": 7, "ideal": 5},
            "SPIN":   {"min": 2, "max": 3, "ideal": 3},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 2, "SPIN": 2},
        "archetype_weights": {
            "Utility Seamer": 22, "Bowling All-rounder": 22, "Accumulator": 20,
            "Economy Seamer": 20, "Utility Spinner": 18, "True All-rounder": 16,
            "Anchor": 16, "Death Specialist": 14, "Economy King": 14,
            "Batting All-rounder": 12, "Wicket Taker": 12, "Powerplay Enforcer": 10,
            "Finisher": 10, "Aggressor": 8, "Impact Player": 6, "Power Hitter": 4,
        },
        "preferred_traits": ["Technically Sound", "Pressure Player", "Consistent", "Economy Focused"],
        "avoided_traits":   ["Volatile", "Temperamental", "Expensive but Effective"],
        "scare_bid_tendency": "very_low",
        "budget_aggressiveness": "conservative",
        "value_ceiling_cr": 14,
        "marquee_bonus_multi": 0.75,
        "retentions": ["Shubman Gill", "Rashid Khan", "B Sai Sudharsan"],
        "rival_teams": [],
        "philosophy": "System over stars. Hard value ceiling. Cold and methodical.",
    },

    "LSG": {
        "id": "LSG",
        "name": "Lucknow Super Giants",
        "short_name": "LSG",
        "color": "#A72B2A",
        "budget": 100,
        "squad_targets": {
            "BAT":    {"min": 4, "max": 6, "ideal": 5},
            "WK-BAT": {"min": 1, "max": 2, "ideal": 1},
            "ALL":    {"min": 2, "max": 4, "ideal": 3},
            "PACE":   {"min": 5, "max": 7, "ideal": 7},
            "SPIN":   {"min": 2, "max": 3, "ideal": 2},
        },
        "playing_xi": {"BAT": 4, "WK-BAT": 1, "ALL": 2, "PACE": 3, "SPIN": 1},
        "archetype_weights": {
            "Anchor": 24, "Death Specialist": 22, "Batting All-rounder": 18,
            "True All-rounder": 18, "Finisher": 16, "Economy Seamer": 16,
            "Powerplay Enforcer": 14, "Aggressor": 12, "Bowling All-rounder": 12,
            "Economy King": 10, "Wicket Taker": 10, "Accumulator": 10,
            "Impact Player": 10, "Power Hitter": 8, "Utility Seamer": 8, "Utility Spinner": 6,
        },
        "preferred_traits": ["Match Winner", "Clutch", "Leader", "Big Match Player", "Pressure Player"],
        "avoided_traits":   ["Inconsistent", "Volatile"],
        "scare_bid_tendency": "medium",
        "budget_aggressiveness": "balanced",
        "value_ceiling_cr": 20,
        "marquee_bonus_multi": 1.25,
        "retentions": ["Nicholas Pooran", "Ravi Bishnoi", "Mohsin Khan"],
        "rival_teams": ["MI", "CSK"],
        "philosophy": "Blow 40-50% on 2 marquee players, fill rest efficiently.",
    },
}

ALL_TEAM_IDS = list(TEAM_CONFIGS.keys())


def get_starting_budget(team_id: str, num_retentions: int) -> float:
    cost = sum(RETENTION_SLABS[:num_retentions])
    return 100.0 - cost


def get_retained_player_names(team_id: str) -> List[str]:
    return list(TEAM_CONFIGS[team_id]["retentions"])
